update

diff --git a/online_quotation/php-dockerfile b/online_quotation/php-dockerfile
--- a/online_quotation/php-dockerfile
+++ b/online_quotation/php-dockerfile
@@ -1,53 +1,77 @@
-ARG ALPINE_VERSION=3.19
-FROM alpine:${ALPINE_VERSION}
-LABEL Maintainer="Tim de Pater <code@trafex.nl>"
-LABEL Description="Lightweight container with Nginx 1.24 & PHP 8.3 based on Alpine Linux."
-# Setup document root
-WORKDIR /var/www/html
 
-# Install packages and remove default server definition
-RUN apk add --no-cache \
-  curl \
-  nginx \
-  php83 \
-  php83-ctype \
-  php83-curl \
-  php83-dom \
-  php83-fileinfo \
-  php83-fpm \
-  php83-gd \
-  php83-intl \
-  php83-mbstring \
-  php83-mysqli \
-  php83-opcache \
-  php83-openssl \
-  php83-phar \
-  php83-session \
-  php83-tokenizer \
-  php83-xml \
-  php83-xmlreader \
-  php83-xmlwriter 
+# OASIS Web
+# 2023/09/28
 
+FROM php:8.3-fpm
 
-# Configure PHP-FPM
-ENV PHP_INI_DIR /etc/php83
-COPY config/fpm-pool.conf ${PHP_INI_DIR}/php-fpm.d/www.conf
-COPY config/php.ini ${PHP_INI_DIR}/conf.d/custom.ini
+ENV PHP_MEMORY_LIMIT=256M
+ENV DEBIAN_FRONTEND=nonintercative
 
-# Configure supervisord
-COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
+RUN apt-get update && apt-get install -y \
+		vim \
+		curl \
+        sendmail \
+        libfreetype6-dev \
+        libjpeg62-turbo-dev \
+        libpng-dev \
+        zlib1g-dev \
+        libzip-dev \
+        unzip \
+		libbz2-dev \
+		libgmp-dev \
+		libicu-dev \
+		libjpeg-dev \
+		libldap2-dev \
+		libmemcached-dev \
+		libmagickwand-dev \
+		libpq-dev \
+        libmagickwand-dev --no-install-recommends && rm -rf /var/lib/apt/lists/* 
 
-# Make sure files/folders needed by the processes are accessable when they run under the nobody user
-RUN chown -R nobody.nobody /var/www/html /run /var/lib/nginx /var/log/nginx
+RUN docker-php-ext-configure mysqli
+RUN docker-php-ext-install mysqli
+RUN docker-php-ext-install gd
 
-# Create symlink for php
-RUN ln -s /usr/bin/php83 /usr/bin/php
+# RUN echo "nameserver 168.95.1.1" > /etc/resolv.conf && \ 
+    # echo "search companydomain" >> /etc/resolv.conf && \    
+    # command_depending_on_dns_resolution
 
-# Switch to use a non-root user from here on
-USER nobody
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+	docker-php-ext-enable opcache; \
+	{ \
+		echo 'opcache.memory_consumption=256'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# set recommended error logging
+RUN { \
+# https://www.php.net/manual/en/errorfunc.constants.php
+		echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+		echo 'display_errors = Off'; \
+		echo 'display_startup_errors = Off'; \
+		echo 'log_errors = On'; \
+		echo 'error_log = /dev/stderr'; \
+		echo 'log_errors_max_len = 1024'; \
+		echo 'ignore_repeated_errors = On'; \
+		echo 'ignore_repeated_source = Off'; \
+		echo 'html_errors = Off'; \
+	} > /usr/local/etc/php/conf.d/error-logging.ini
 
-# Expose the port nginx is reachable on
-EXPOSE 8000
+RUN set -eux; a2enmod rewrite expires; \
+	\
+	a2enmod remoteip; { \
+		echo 'RemoteIPHeader X-Forwarded-For'; \
+		echo 'RemoteIPTrustedProxy 10.0.0.0/8'; \
+		echo 'RemoteIPTrustedProxy 172.16.0.0/12'; \
+		echo 'RemoteIPTrustedProxy 192.168.0.0/16'; \
+		echo 'RemoteIPTrustedProxy 127.0.0.0/8'; \
+	} > /etc/apache2/conf-available/remoteip.conf; \
+	a2enconf remoteip; \
+# (replace all instances of "%h" with "%a" in LogFormat)
+	find /etc/apache2 -type f -name '*.conf' -exec sed -ri 's/([[:space:]]*LogFormat[[:space:]]+"[^"]*)%h([^"]*")/\1%a\2/g' '{}' +
 
-# Configure a healthcheck to validate that everything is up&running
-HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8000/fpm-ping || exit 1
+EXPOSE 80 443 587 465
+CMD apachectl -D FOREGROUND 
